openapi: 3.0.0
info:
  title: Hermes Demo API
  version: 0.1.0
paths:
  /api/twilio/inbound:
    post:
      summary: Handle inbound Twilio calls
      responses:
        '200': { description: OK }
  /api/twilio/voice-stream:
    post:
      summary: Twilio media stream endpoint
      responses:
        '200': { description: OK }
  /api/twilio/call-log:
    post:
      summary: Log demo calls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallLog'
      responses:
        '200': { description: OK }
  /api/clio/create-matter:
    post:
      summary: Create a Clio matter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Matter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matter'
  /api/clio/sync-contact:
    post:
      summary: Sync contact information
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200': { description: OK }
  /api/clio/time-entry:
    post:
      summary: Create time entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeEntry'
      responses:
        '200': { description: OK }
  /api/clio/log-activity:
    post:
      summary: Log activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Activity'
      responses:
        '200': { description: OK }
components:
  schemas:
    CallLog:
      type: object
      properties:
        caller:
          type: string
        timestamp:
          type: string
    Matter:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
    Contact:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    TimeEntry:
      type: object
      properties:
        description:
          type: string
        duration:
          type: number
    Activity:
      type: object
      properties:
        note:
          type: string
