name: HERMES CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Backend CI (lint + tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with black (check only)
        run: |
          black --version
          black --check .

      - name: Run tests
        env:
          # Provide minimal env to satisfy config where needed
          OPENAI_API_KEY: test-key
          DEBUG: 'true'
        run: |
          pytest -q

  deploy-frontend:
    name: Frontend CD (GitHub Pages)
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write  # required for gh-pages push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages

# ---------------------------------------------
# Notes
# - test-backend: Lints with black and runs pytest on every push and PR to main.
# - deploy-frontend: Builds the marketing site and deploys to gh-pages, but only on push to main, and only after test-backend succeeds (needs).
# - The 'needs' keyword ensures deploy-frontend waits for test-backend to pass.
# - The 'if' condition restricts deploy-frontend to pushes on the main branch.
# - Repository settings required:
#   1) Pages source set to 'Deploy from a branch' -> branch 'gh-pages' (root).
#   2) Actions permissions allow workflows to create and approve pull requests (optional) and, importantly, 'Read and write permissions' for GITHUB_TOKEN so the workflow can push to gh-pages.
#   3) If using organization-level policies, ensure workflows can use third-party actions like 'peaceiris/actions-gh-pages'.
# ---------------------------------------------

